name: Delete Preview Env

on:
  delete:
    branches:
      - 'fix-*'
      - 'feat-*'
      - 'refactor-*'

jobs:
  delete_preview_env:
    runs-on: ubuntu-latest

    permissions:
        contents: read
        id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ vars.STAGING_WIP }}
          service_account: ${{ vars.STAGING_SERVICE_ACCOUNT }}

      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: ${{ vars.STAGING_GKE_CLUSTER_NAME }}
          location: ${{ vars.STAGING_GKE_CLUSTER_REGION }}

      - name: Port forward hydra admin port
        run: |
          kubectl get svc
          kubectl port-forward svc/hydra-admin 8080:4445 &

      - name: Generate Vercel URI
        run: echo "VERCEL_URI=https://${{ github.event.repository.name }}-git-${{ github.event.ref }}-${{ github.repository_owner }}.vercel.app" >> $GITHUB_ENV

      - name: Delete redirect_uris and post_logout_redirect_uris in hydra
        run: |
          CLIENT=$(curl -s localhost:8080/clients/${{ secrets.STAGING_CLIENT_ID }} | jq .)
          REDIRECT_URIS=$(echo $CLIENT | jq  '.redirect_uris -= ["'"$VERCEL_URI"'/api/auth/callback/ocx-idp"] | .redirect_uris')
          REDIRECT_URIS_PAYLOAD=$(echo $REDIRECT_URIS | jq '[{"op": "replace", "path": "/redirect_uris", "value": .}]')
          POST_LOGOUT_URIS_PAYLOAD=$(echo $REDIRECT_URIS_PAYLOAD | jq '[.[] | {op: "replace", path: "/post_logout_redirect_uris", value: [.value[] | sub("/api/auth/callback/ocx-idp"; "")]}]')
          curl -s -X PATCH "http://localhost:8080/clients/ocx-ui-gcp-stg-auth-client" -H 'Content-Type: application/json' -d "$POST_LOGOUT_URIS_PAYLOAD"
          curl -s -X PATCH "http://localhost:8080/clients/ocx-ui-gcp-stg-auth-client" -H 'Content-Type: application/json' -d "$REDIRECT_URIS_PAYLOAD"

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Remove Vercel env var
        run: |
          if vercel env ls preview ${{ github.event.ref }} --token=${{ secrets.VERCEL_TOKEN }} | grep -q NEXTAUTH_URL ; then
            vercel env rm NEXTAUTH_URL preview ${{ github.event.ref }} --yes --token=${{ secrets.VERCEL_TOKEN }}
          fi
      # write on pr comment
      # caceh
